Add Server Request Body support
holepunchto/bare-http1 pull request #12
Opened 2024-05-23 23:00 UTC by yassernasc

'Cherry-picked' a commit from https://github.com/holepunchto/bare-http1/pull/11, the first merged will have it 😅.

2024-05-24 07:11 UTC, kasperisager requested changes
Looks good! I think the only thing missing is chunked encoding support, which you should be able to copy verbatim from `ClientConnection`. As mentioned previously, we should make a proper parser abstraction eventually, but let's leave that for later when all the bits are in place.

2024-05-24 21:27 UTC, yassernasc commented
The unified parser abstraction will be a great refactoring, `chunked encoding` support added.

2024-05-27 08:06 UTC, kasperisager commented on lib/client-connection.js
> +    if (this.req) this.req._continueWrite()
Good catch!

2024-05-27 08:12 UTC, kasperisager requested changes

2024-05-27 08:12 UTC, kasperisager commented on test.js
> +    setTimeout(() => { req.end(Buffer.alloc(2 * 1024 * 1024, 'asdf')) })
```suggestion
    setImmediate(() => { req.end(Buffer.alloc(2 * 1024 * 1024, 'asdf')) })
```

2024-05-27 08:13 UTC, kasperisager approved these changes

2024-05-27 08:17 UTC, merged