Timeout
holepunchto/bare-http1 pull request #14
Opened 2024-07-01 23:08 UTC by yassernasc

Added `setTimeouts` and `timeout` events for all: ClientRequest, Server, ServerResponse, IncomingMessage and Outgoing Message. Also the `server.timeout` prop.

Maybe I went too far at this PR, no problem at cutting extra pieces. The only 'timeout's not included are `headersTimeout`, `requestTimeout` and `keepAliveTimeout`.

---

The second commit (https://github.com/holepunchto/bare-http1/commit/c1591117ae024e537b3c4e82dd72d4fdc0acd17d) adds the behavior:

> If no 'timeout' listener is added to the request, the response, or the server, then sockets are destroyed when they time out. If a handler is assigned to the request, the response, or the server's 'timeout' events, timed out sockets must be handled explicitly.

Copycat from: https://github.com/nodejs/node/blob/6671f7ef6fa923a254fc1c48a84c7a9203420c32/lib/_http_server.js#L786

If this behavior isn't interesting for us, we can easily revert the commit.

2024-07-02 08:18 UTC, kasperisager requested changes
Looks solid! I think the upgrade handling is the only missing bit. Could you add some tests for that as well?

Another ting to investigate is whether or not the timeout itself is affected by upgrades, which I _don't_ think it is. That is, in Node.js, what happens when a server socket times out after upgrade? The `timeout` listener is removed on upgrade, so it ought to be destroyed if the timeout itself is unaffected.

2024-07-02 08:18 UTC, kasperisager commented on lib/server.js
> +      }
We should move this and the `_ontimeout()` method to `HTTPServerConnection` so it's easy to add this missing bit: On upgrade, the `timeout` listener should be removed from the socket.

2024-07-02 19:43 UTC, yassernasc commented
Well pointed, I've added tests and fixed the `upgrade` issue for both client and server sides.

2024-07-03 07:51 UTC, kasperisager requested changes

2024-07-03 07:51 UTC, kasperisager commented on lib/server.js
> +      if (this._timeout) optsClone.timeout = this._timeout
You can remove this and just use `this.server.timeout` in `HTTPServerConnection`.

2024-07-03 11:30 UTC, kasperisager approved these changes
💯

2024-07-03 11:32 UTC, merged